import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ItemList from "@/components/ItemList/ItemList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const sampleData = [
    { id: 1, name: "John" },
    { id: 2, name: "Mary" },
    { id: 3, name: "Bob" },
    { id: 4, name: "Alice" },
  ];

  return (
    <>
      <Head>
        <title>Filter Items</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <ItemList items={sampleData} />
        </div>
      </main>
    </>
  );
}
